services:
   mysql:
    image: mysql:latest
    container_name: yelp_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yelp_db
    volumes:
      - yelpdb-data:/var/lib/mysql

volumes:
  yelpdb-data: 